### ISSUE TITLE
Cannot find module 'Data.Maybe'

### ISSUE THREAD

**Issue by obmarg** [Risto-Stevcev/purescript-ffi-utils#1]
I'm building an node application in purescript using purescript-ffi-utils.  Everything builds fine, but when I run it, I get a `Error: Cannot find module 'Data.Maybe'` which originates from `output/FFI.Util/foreign.js:3:13`.

Having a look around the rest of the code that purescript outputs, it seems like it's common to use relative imports instead of absolute.  I'm not sure if this is something unique to my environment/build though?

**Comment by Risto-Stevcev** [comment]
Thanks for creating this issue. It should be fixed now. Let me know if you're still running into issues and I'll reopen this ticket

**Comment by obmarg** [comment]
Thanks @Risto-Stevcev that's worked nicely 👍
