### ISSUE TITLE
Cannot find module "Data.Maybe" when importing Functions.purs

### ISSUE THREAD

**Issue by biern** [Risto-Stevcev/purescript-ffi-utils#4]
I'm using ffi utils v3 with webpack and get the following error only when importing something from `FFi.Util.Function`:
```
ERROR in ./bower_components/purescript-ffi-utils/src/FFI/Util/Function.js
Module not found: Error: Can't resolve 'Data.Maybe' in '(...)/bower_components/purescript-ffi-utils/src/FFI/Util'
 @ ./bower_components/purescript-ffi-utils/src/FFI/Util/Function.js 3:12-33
 @ ./bower_components/purescript-ffi-utils/src/FFI/Util/Function.purs
```
I'm wondering if this module needs some extra configuration to use in webpack or it's something else?

**Comment by Risto-Stevcev** [comment]
What steps did you take to get to the error? I'll replicate it on my machine. I think it's a webpack misconfiguration

**Comment by biern** [comment]
Ok, so this is far from the minimal setup, but it reproduces the problem. I'm getting it with this webpack config: https://github.com/alexmingoia/pux-starter-app/blob/master/webpack.config.js
To reproduce:
```
git clone https://github.com/alexmingoia/pux-starter-app foo
cd foo
npm install
bower install purescript-ffi-utils@2  # This project uses aff3, so v2 is necessary. I'm getting the same problem with ffi-utils 2 and 3 though.
```
After adding `import FFI.Util.Function (call0)` to `Main.purs` the app will fail to load after `npm start`, `npm run build` will fail as well.

**Comment by Risto-Stevcev** [comment]
Ah ok, I see what the problem is. Add this entry to `resolve.alias` for now:
```js
    alias: {
      'react': 'preact-compat',
      'react-dom': 'preact-compat',
      'create-react-class': 'preact-compat/lib/create-react-class',
      'Data.Maybe': path.join(__dirname, './output/Data.Maybe')
    },
```

In the meantime I'll push up a fix that will work without this sort of thing

**Comment by Risto-Stevcev** [comment]
I pushed up `v4.0.0`. Pux and/or the starter app needs to be updated to use Aff 4 though

**Comment by biern** [comment]
@Risto-Stevcev Thanks, I appreciate taking the time to fix it. I'm using v4 now at it works like a charm!
